# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embedding.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "embedding.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0f\x65mbedding.proto\x12\x18llm_gateway.embedding.v1"\x99\x01\n\x0f\x45mbedRowRequest\x12\x11\n\tworkup_id\x18\x01 \x01(\x03\x12\x15\n\rsubmission_id\x18\x02 \x01(\t\x12\x12\n\ndisease_id\x18\x03 \x01(\t\x12\x14\n\x0csection_type\x18\x04 \x01(\t\x12\x1b\n\x13student_answer_text\x18\x05 \x01(\t\x12\x15\n\rfeedback_text\x18\x06 \x01(\t"\xeb\x01\n\x10\x45mbedRowResponse\x12\x11\n\tworkup_id\x18\x01 \x01(\x03\x12\x15\n\rsubmission_id\x18\x02 \x01(\t\x12\x12\n\ndisease_id\x18\x03 \x01(\t\x12\x14\n\x0csection_type\x18\x04 \x01(\t\x12\x1b\n\x13student_answer_text\x18\x05 \x01(\t\x12\x1d\n\x15student_answer_vector\x18\x06 \x03(\x02\x12\x15\n\rfeedback_text\x18\x07 \x01(\t\x12\x17\n\x0f\x66\x65\x65\x64\x62\x61\x63k_vector\x18\x08 \x03(\x02\x12\x17\n\x0f\x65mbedding_model\x18\t \x01(\t"\x9a\x01\n\x11\x45mbedBatchRequest\x12\x37\n\x04rows\x18\x01 \x03(\x0b\x32).llm_gateway.embedding.v1.EmbedRowRequest\x12\x16\n\x0emodel_provider\x18\x02 \x01(\t\x12\x12\n\nmodel_name\x18\x03 \x01(\t\x12\x10\n\x08trace_id\x18\x04 \x01(\t\x12\x0e\n\x06job_id\x18\x05 \x01(\t"N\n\x12\x45mbedBatchResponse\x12\x38\n\x04rows\x18\x01 \x03(\x0b\x32*.llm_gateway.embedding.v1.EmbedRowResponse2s\n\x08\x45mbedder\x12g\n\nEmbedBatch\x12+.llm_gateway.embedding.v1.EmbedBatchRequest\x1a,.llm_gateway.embedding.v1.EmbedBatchResponseB\x1a\xaa\x02\x17LlmGateway.Embedding.V1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "embedding_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"\252\002\027LlmGateway.Embedding.V1"
    _globals["_EMBEDROWREQUEST"]._serialized_start = 46
    _globals["_EMBEDROWREQUEST"]._serialized_end = 199
    _globals["_EMBEDROWRESPONSE"]._serialized_start = 202
    _globals["_EMBEDROWRESPONSE"]._serialized_end = 437
    _globals["_EMBEDBATCHREQUEST"]._serialized_start = 440
    _globals["_EMBEDBATCHREQUEST"]._serialized_end = 594
    _globals["_EMBEDBATCHRESPONSE"]._serialized_start = 596
    _globals["_EMBEDBATCHRESPONSE"]._serialized_end = 674
    _globals["_EMBEDDER"]._serialized_start = 676
    _globals["_EMBEDDER"]._serialized_end = 791
# @@protoc_insertion_point(module_scope)
