# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import gateway.grader.v1.grader_pb2 as grader__pb2

GRPC_GENERATED_VERSION = "1.75.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in grader_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class GraderStub:
    """Errors travel via gRPC status, with gateway placing a string code in metadata:
    Transient:  "network_error","provider_timeout","rate_limited","schema_mismatch"
    Terminal:   "invalid_rubric","unsupported_model","auth_failed","invalid_payload"

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Grade = channel.unary_unary(
            "/grader.v1.Grader/Grade",
            request_serializer=grader__pb2.GradeRequest.SerializeToString,
            response_deserializer=grader__pb2.GradeResponse.FromString,
            _registered_method=True,
        )


class GraderServicer:
    """Errors travel via gRPC status, with gateway placing a string code in metadata:
    Transient:  "network_error","provider_timeout","rate_limited","schema_mismatch"
    Terminal:   "invalid_rubric","unsupported_model","auth_failed","invalid_payload"

    """

    def Grade(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_GraderServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Grade": grpc.unary_unary_rpc_method_handler(
            servicer.Grade,
            request_deserializer=grader__pb2.GradeRequest.FromString,
            response_serializer=grader__pb2.GradeResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("grader.v1.Grader", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("grader.v1.Grader", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Grader:
    """Errors travel via gRPC status, with gateway placing a string code in metadata:
    Transient:  "network_error","provider_timeout","rate_limited","schema_mismatch"
    Terminal:   "invalid_rubric","unsupported_model","auth_failed","invalid_payload"

    """

    @staticmethod
    def Grade(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/grader.v1.Grader/Grade",
            grader__pb2.GradeRequest.SerializeToString,
            grader__pb2.GradeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
