# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grader.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "grader.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0cgrader.proto\x12\tgrader.v1"F\n\x0f\x46\x65\x65\x64\x62\x61\x63kSection\x12\r\n\x05score\x18\x01 \x01(\t\x12\x12\n\nevaluation\x18\x02 \x01(\t\x12\x10\n\x08\x66\x65\x65\x64\x62\x61\x63k\x18\x03 \x01(\t"\x82\x02\n\x0fProblemFeedback\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0bis_priority\x18\x02 \x01(\x08\x12\x32\n\x0eidentification\x18\x03 \x01(\x0b\x32\x1a.grader.v1.FeedbackSection\x12/\n\x0b\x65xplanation\x18\x04 \x01(\x0b\x32\x1a.grader.v1.FeedbackSection\x12\x37\n\x13plan_recommendation\x18\x05 \x01(\x0b\x32\x1a.grader.v1.FeedbackSection\x12.\n\nmonitoring\x18\x06 \x01(\x0b\x32\x1a.grader.v1.FeedbackSection"\x88\x01\n\x0cGradeRequest\x12\x15\n\rsystem_prompt\x18\x01 \x01(\t\x12\x13\n\x0buser_prompt\x18\x02 \x01(\t\x12\x16\n\x0emodel_provider\x18\x03 \x01(\t\x12\x12\n\nmodel_name\x18\x04 \x01(\t\x12\x10\n\x08trace_id\x18\x05 \x01(\t\x12\x0e\n\x06job_id\x18\x06 \x01(\t"=\n\rGradeResponse\x12,\n\x08\x66\x65\x65\x64\x62\x61\x63k\x18\x01 \x01(\x0b\x32\x1a.grader.v1.ProblemFeedback2D\n\x06Grader\x12:\n\x05Grade\x12\x17.grader.v1.GradeRequest\x1a\x18.grader.v1.GradeResponseB\x0c\xaa\x02\tGrader.V1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "grader_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"\252\002\tGrader.V1"
    _globals["_FEEDBACKSECTION"]._serialized_start = 27
    _globals["_FEEDBACKSECTION"]._serialized_end = 97
    _globals["_PROBLEMFEEDBACK"]._serialized_start = 100
    _globals["_PROBLEMFEEDBACK"]._serialized_end = 358
    _globals["_GRADEREQUEST"]._serialized_start = 361
    _globals["_GRADEREQUEST"]._serialized_end = 497
    _globals["_GRADERESPONSE"]._serialized_start = 499
    _globals["_GRADERESPONSE"]._serialized_end = 560
    _globals["_GRADER"]._serialized_start = 562
    _globals["_GRADER"]._serialized_end = 630
# @@protoc_insertion_point(module_scope)
